### ISSUE TITLE
HowTo Install Skin on a VTI receiver

### ISSUE THREAD

**Issue by MoritzSa** [feuster/Enigma2_TechniSat_Skins#1]
Can you describe how I install this skin on a satellite receiver based on a vti image? Thanks in advance.

**Comment by feuster** [comment]
If a STB Enigma² image supports skins there are following steps to do:

1. Upload one or more skin folders via FTP to `/usr/share/enigma2`
2. In main menu submenu `Settings -> System -> Skin`select the desired skin

**Comment by feuster** [comment]
[VU+ Wiki](https://wiki.vuplus-support.org/index.php?title=Skin)
![Skin Menu Screenshot](https://wiki.vuplus-support.org/images/thumb/4/45/Skin_Auswahlmen%C3%BC.png/800px-Skin_Auswahlmen%C3%BC.png)

Since this issue should be solved -> __closed__
